# Generated by Django 4.0.2 on 2023-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_rename_request_req'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='id',
        ),
        migrations.AddField(
            model_name='req',
            name='r_id',
            field=models.AutoField(default=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
