# Generated by Django 4.0.2 on 2023-04-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_req_id_req_r_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req',
            name='r_id',
        ),
        migrations.AddField(
            model_name='req',
            name='id',
            field=models.BigAutoField(auto_created=True, default=100, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
